name: External Events
on:
  repository_dispatch:
    types: [build]

jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      #To access the inputs
      -run: echo "Repository Dispatch"



