name: Matrix
on: [push]

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 15, 16]
    steps:
      - name: default node version
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: new version
      - run: node -v