name: Repository Events
on:
  push:
  pull_request: [opened, assigned, reopened]
  issues: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4